# Generated by Django 3.1.2 on 2021-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='result',
            field=models.CharField(max_length=200),
        ),
    ]
